version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 435756741830.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=435756741830.dkr.ecr.ap-south-1.amazonaws.com/java-api
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t java-api:$IMAGE_TAG .
      - docker tag java-api:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating Lambda function...
      - aws lambda update-function-code --function-name java-serverless-api --image-uri $REPOSITORY_URI:$IMAGE_TAG
      - echo Deployment completed